# Generated by Django 6.1.1 on 2026-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('major', models.CharField(choices=[('major', 'Computer Science')], max_length=100)),
                ('grad_year', models.IntegerField()),
                ('class_standing', models.CharField(choices=[('freshman', 'Freshman'), ('sophomore', 'Sophomore'), ('junior', 'Junior'), ('senior', 'Senior')], max_length=100)),
                ('comments', models.TextField()),
                ('languages', models.CharField(max_length=100)),
            ],
        ),
    ]
